export const kickers: string[] = [
    "Keep scrolling, it gets better!",
    "The sequel you've been waiting for!",
    "Next up: Even more brilliance!",
    "Don't stop now, it's a rollercoaster!",
    "Bet you didn't see this coming!",
    "Hold onto your hats, it's a wild one!",
    "Spoiler alert: It's amazing!",
    "From the creators of the last project...",
    "This way to the good stuff!",
    "Another masterpiece awaits!",
    "Ugh, fine. Here's another one.",
    "You're not ready for this, babe.",
    "Can you even handle what's next?",
    "Okay, but this one's iconic.",
    "Keep up, sweetie. There's more.",
    "Serving you next-level realness.",
    "Don't act like you're not obsessed.",
    "Another slay incoming.",
    "More? You're sooo needy.",
    "Oh, you're still here? Cute.",
    "You're welcome for what's next.",
    "Try not to freak out, OK?",
    "This one's literally perfect, no big deal.",
    "Another banger? Obviously.",
    "Don't say I never give you anything.",
    "Brace yourself, it's major.",
    "You're obsessed, just admit it.",
    "Another slay, no skips.",
    "Whispers of what's next...",
    "The plot thickens.",
    "This way to the rabbit hole.",
    "Next project? Bold of you to assume.",
    "Still not tired of me? Wow.",
    "Prepare your eyeballs for greatness.",
    "What's behind door number two?",
    "It's giving... another project.",
    "If you liked that, you'll love this.",
    "Another project? Don't mind if I do.",
    "Coming up: pure chaos, probably.",
    "This one will change your life (maybe).",
]